// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import ErrorsController from "./errors_controller"
application.register("errors", ErrorsController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import ResourceController from "./resource_controller"
application.register("resource", ResourceController)
